plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.jasaedukasi.presensiedukasi'
    compileSdk 36

    defaultConfig {
        applicationId "com.jasaedukasi.presensiedukasi"
        minSdk 21
        targetSdk 36
        versionCode 1
        versionName "1.0.6"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    androidComponents {
        onVariants(selector().all()) { variant ->
            variant.outputs.forEach { output ->
                output.outputFileName.set("PresensiEdukasi-v${android.defaultConfig.versionName}-${variant.buildType}.apk")
            }
        }
    }
}

dependencies {
    implementation libs.appcompat
    implementation libs.material
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
}
